// Autogenerated from Pigeon (v26.1.10), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, omit_obvious_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    return a.length == b.length &&
        a.entries.every(
          (MapEntry<Object?, Object?> entry) =>
              (b as Map<Object?, Object?>).containsKey(entry.key) &&
              _deepEquals(entry.value, b[entry.key]),
        );
  }
  return a == b;
}

enum ThermalStateData { nominal, fair, serious, critical, unknown }

enum SensorKindData { cpu, gpu, memory, ambient, other }

enum FanModeData { automatic, manual }

class SensorReadingData {
  SensorReadingData({this.id, this.name, this.unit, this.value, this.kind});

  String? id;

  String? name;

  String? unit;

  double? value;

  SensorKindData? kind;

  List<Object?> _toList() {
    return <Object?>[id, name, unit, value, kind];
  }

  Object encode() {
    return _toList();
  }

  static SensorReadingData decode(Object result) {
    result as List<Object?>;
    return SensorReadingData(
      id: result[0] as String?,
      name: result[1] as String?,
      unit: result[2] as String?,
      value: result[3] as double?,
      kind: result[4] as SensorKindData?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SensorReadingData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class FanReadingData {
  FanReadingData({
    this.id,
    this.name,
    this.currentRpm,
    this.minimumRpm,
    this.maximumRpm,
    this.targetRpm,
    this.mode,
  });

  String? id;

  String? name;

  int? currentRpm;

  int? minimumRpm;

  int? maximumRpm;

  int? targetRpm;

  FanModeData? mode;

  List<Object?> _toList() {
    return <Object?>[
      id,
      name,
      currentRpm,
      minimumRpm,
      maximumRpm,
      targetRpm,
      mode,
    ];
  }

  Object encode() {
    return _toList();
  }

  static FanReadingData decode(Object result) {
    result as List<Object?>;
    return FanReadingData(
      id: result[0] as String?,
      name: result[1] as String?,
      currentRpm: result[2] as int?,
      minimumRpm: result[3] as int?,
      maximumRpm: result[4] as int?,
      targetRpm: result[5] as int?,
      mode: result[6] as FanModeData?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! FanReadingData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class HardwareCapabilitiesData {
  HardwareCapabilitiesData({
    this.supportsRawSensors,
    this.supportsFanControl,
    this.hasFans,
    this.backend,
    this.note,
  });

  bool? supportsRawSensors;

  bool? supportsFanControl;

  bool? hasFans;

  String? backend;

  String? note;

  List<Object?> _toList() {
    return <Object?>[
      supportsRawSensors,
      supportsFanControl,
      hasFans,
      backend,
      note,
    ];
  }

  Object encode() {
    return _toList();
  }

  static HardwareCapabilitiesData decode(Object result) {
    result as List<Object?>;
    return HardwareCapabilitiesData(
      supportsRawSensors: result[0] as bool?,
      supportsFanControl: result[1] as bool?,
      hasFans: result[2] as bool?,
      backend: result[3] as String?,
      note: result[4] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HardwareCapabilitiesData ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class HardwareSnapshotData {
  HardwareSnapshotData({
    this.capturedAtEpochMs,
    this.thermalState,
    this.sensors,
    this.fans,
    this.note,
  });

  int? capturedAtEpochMs;

  ThermalStateData? thermalState;

  List<SensorReadingData?>? sensors;

  List<FanReadingData?>? fans;

  String? note;

  List<Object?> _toList() {
    return <Object?>[capturedAtEpochMs, thermalState, sensors, fans, note];
  }

  Object encode() {
    return _toList();
  }

  static HardwareSnapshotData decode(Object result) {
    result as List<Object?>;
    return HardwareSnapshotData(
      capturedAtEpochMs: result[0] as int?,
      thermalState: result[1] as ThermalStateData?,
      sensors: (result[2] as List<Object?>?)?.cast<SensorReadingData?>(),
      fans: (result[3] as List<Object?>?)?.cast<FanReadingData?>(),
      note: result[4] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HardwareSnapshotData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is ThermalStateData) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is SensorKindData) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is FanModeData) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    } else if (value is SensorReadingData) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is FanReadingData) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is HardwareCapabilitiesData) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is HardwareSnapshotData) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : ThermalStateData.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : SensorKindData.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : FanModeData.values[value];
      case 132:
        return SensorReadingData.decode(readValue(buffer)!);
      case 133:
        return FanReadingData.decode(readValue(buffer)!);
      case 134:
        return HardwareCapabilitiesData.decode(readValue(buffer)!);
      case 135:
        return HardwareSnapshotData.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class HardwareHostApi {
  /// Constructor for [HardwareHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  HardwareHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<HardwareCapabilitiesData> getCapabilities() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mac_fan_tool.HardwareHostApi.getCapabilities$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    )!;
    return pigeonVar_replyValue as HardwareCapabilitiesData;
  }

  Future<HardwareSnapshotData> getSnapshot() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mac_fan_tool.HardwareHostApi.getSnapshot$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    )!;
    return pigeonVar_replyValue as HardwareSnapshotData;
  }

  Future<void> setFanMode(String fanId, FanModeData mode) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mac_fan_tool.HardwareHostApi.setFanMode$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[fanId, mode],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setFanTargetRpm(String fanId, int targetRpm) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mac_fan_tool.HardwareHostApi.setFanTargetRpm$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[fanId, targetRpm],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}
