// Autogenerated from Pigeon (v26.1.10), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsHardwareApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsHardwareApi(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsHardwareApi(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashHardwareApi(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashHardwareApi(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashHardwareApi(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

enum ThermalStateData: Int {
  case nominal = 0
  case fair = 1
  case serious = 2
  case critical = 3
  case unknown = 4
}

enum SensorKindData: Int {
  case cpu = 0
  case gpu = 1
  case memory = 2
  case ambient = 3
  case other = 4
}

enum FanModeData: Int {
  case automatic = 0
  case manual = 1
}

/// Generated class from Pigeon that represents data sent in messages.
struct SensorReadingData: Hashable {
  var id: String? = nil
  var name: String? = nil
  var unit: String? = nil
  var value: Double? = nil
  var kind: SensorKindData? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SensorReadingData? {
    let id: String? = nilOrValue(pigeonVar_list[0])
    let name: String? = nilOrValue(pigeonVar_list[1])
    let unit: String? = nilOrValue(pigeonVar_list[2])
    let value: Double? = nilOrValue(pigeonVar_list[3])
    let kind: SensorKindData? = nilOrValue(pigeonVar_list[4])

    return SensorReadingData(
      id: id,
      name: name,
      unit: unit,
      value: value,
      kind: kind
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      name,
      unit,
      value,
      kind,
    ]
  }
  static func == (lhs: SensorReadingData, rhs: SensorReadingData) -> Bool {
    return deepEqualsHardwareApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashHardwareApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct FanReadingData: Hashable {
  var id: String? = nil
  var name: String? = nil
  var currentRpm: Int64? = nil
  var minimumRpm: Int64? = nil
  var maximumRpm: Int64? = nil
  var targetRpm: Int64? = nil
  var mode: FanModeData? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FanReadingData? {
    let id: String? = nilOrValue(pigeonVar_list[0])
    let name: String? = nilOrValue(pigeonVar_list[1])
    let currentRpm: Int64? = nilOrValue(pigeonVar_list[2])
    let minimumRpm: Int64? = nilOrValue(pigeonVar_list[3])
    let maximumRpm: Int64? = nilOrValue(pigeonVar_list[4])
    let targetRpm: Int64? = nilOrValue(pigeonVar_list[5])
    let mode: FanModeData? = nilOrValue(pigeonVar_list[6])

    return FanReadingData(
      id: id,
      name: name,
      currentRpm: currentRpm,
      minimumRpm: minimumRpm,
      maximumRpm: maximumRpm,
      targetRpm: targetRpm,
      mode: mode
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      name,
      currentRpm,
      minimumRpm,
      maximumRpm,
      targetRpm,
      mode,
    ]
  }
  static func == (lhs: FanReadingData, rhs: FanReadingData) -> Bool {
    return deepEqualsHardwareApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashHardwareApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct HardwareCapabilitiesData: Hashable {
  var supportsRawSensors: Bool? = nil
  var supportsFanControl: Bool? = nil
  var hasFans: Bool? = nil
  var backend: String? = nil
  var note: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HardwareCapabilitiesData? {
    let supportsRawSensors: Bool? = nilOrValue(pigeonVar_list[0])
    let supportsFanControl: Bool? = nilOrValue(pigeonVar_list[1])
    let hasFans: Bool? = nilOrValue(pigeonVar_list[2])
    let backend: String? = nilOrValue(pigeonVar_list[3])
    let note: String? = nilOrValue(pigeonVar_list[4])

    return HardwareCapabilitiesData(
      supportsRawSensors: supportsRawSensors,
      supportsFanControl: supportsFanControl,
      hasFans: hasFans,
      backend: backend,
      note: note
    )
  }
  func toList() -> [Any?] {
    return [
      supportsRawSensors,
      supportsFanControl,
      hasFans,
      backend,
      note,
    ]
  }
  static func == (lhs: HardwareCapabilitiesData, rhs: HardwareCapabilitiesData) -> Bool {
    return deepEqualsHardwareApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashHardwareApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct HardwareSnapshotData: Hashable {
  var capturedAtEpochMs: Int64? = nil
  var thermalState: ThermalStateData? = nil
  var sensors: [SensorReadingData?]? = nil
  var fans: [FanReadingData?]? = nil
  var note: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HardwareSnapshotData? {
    let capturedAtEpochMs: Int64? = nilOrValue(pigeonVar_list[0])
    let thermalState: ThermalStateData? = nilOrValue(pigeonVar_list[1])
    let sensors: [SensorReadingData?]? = nilOrValue(pigeonVar_list[2])
    let fans: [FanReadingData?]? = nilOrValue(pigeonVar_list[3])
    let note: String? = nilOrValue(pigeonVar_list[4])

    return HardwareSnapshotData(
      capturedAtEpochMs: capturedAtEpochMs,
      thermalState: thermalState,
      sensors: sensors,
      fans: fans,
      note: note
    )
  }
  func toList() -> [Any?] {
    return [
      capturedAtEpochMs,
      thermalState,
      sensors,
      fans,
      note,
    ]
  }
  static func == (lhs: HardwareSnapshotData, rhs: HardwareSnapshotData) -> Bool {
    return deepEqualsHardwareApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashHardwareApi(value: toList(), hasher: &hasher)
  }
}

private class HardwareApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ThermalStateData(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return SensorKindData(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return FanModeData(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      return SensorReadingData.fromList(self.readValue() as! [Any?])
    case 133:
      return FanReadingData.fromList(self.readValue() as! [Any?])
    case 134:
      return HardwareCapabilitiesData.fromList(self.readValue() as! [Any?])
    case 135:
      return HardwareSnapshotData.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class HardwareApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? ThermalStateData {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? SensorKindData {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? FanModeData {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? SensorReadingData {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? FanReadingData {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? HardwareCapabilitiesData {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? HardwareSnapshotData {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class HardwareApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return HardwareApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return HardwareApiPigeonCodecWriter(data: data)
  }
}

class HardwareApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = HardwareApiPigeonCodec(readerWriter: HardwareApiPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol HardwareHostApi {
  func getCapabilities() throws -> HardwareCapabilitiesData
  func getSnapshot() throws -> HardwareSnapshotData
  func setFanMode(fanId: String, mode: FanModeData) throws
  func setFanTargetRpm(fanId: String, targetRpm: Int64) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class HardwareHostApiSetup {
  static var codec: FlutterStandardMessageCodec { HardwareApiPigeonCodec.shared }
  /// Sets up an instance of `HardwareHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: HardwareHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getCapabilitiesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mac_fan_tool.HardwareHostApi.getCapabilities\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCapabilitiesChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getCapabilities()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getCapabilitiesChannel.setMessageHandler(nil)
    }
    let getSnapshotChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mac_fan_tool.HardwareHostApi.getSnapshot\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getSnapshotChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getSnapshot()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getSnapshotChannel.setMessageHandler(nil)
    }
    let setFanModeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mac_fan_tool.HardwareHostApi.setFanMode\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setFanModeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let fanIdArg = args[0] as! String
        let modeArg = args[1] as! FanModeData
        do {
          try api.setFanMode(fanId: fanIdArg, mode: modeArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setFanModeChannel.setMessageHandler(nil)
    }
    let setFanTargetRpmChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mac_fan_tool.HardwareHostApi.setFanTargetRpm\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setFanTargetRpmChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let fanIdArg = args[0] as! String
        let targetRpmArg = args[1] as! Int64
        do {
          try api.setFanTargetRpm(fanId: fanIdArg, targetRpm: targetRpmArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setFanTargetRpmChannel.setMessageHandler(nil)
    }
  }
}
